default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: clouduser
  password: Qwerty14@
  pool: 25

development:
  <<: *default
  database: postgres
  pool: 25

test:
  <<: *default
  database: postgres_test

production:
  <<: *default
  database: postgres
  username: clouduser
  password: Qwerty14@
  pool: 25

